@baseUrl = http://localhost:3000

### 1. Checkout Complexo (Sucesso - Cartão começa com 4)
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "usr": "Guilherme",
  "eml": "gui@fullcycle.com.br",
  "pwd": "senhaforte",
  "c_id": 2,
  "card": "4111222233334444"
}

### 2. Checkout Complexo (Erro - Pagamento recusado)
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
  "usr": "João",
  "eml": "joao@teste.com",
  "pwd": "123",
  "c_id": 1,
  "card": "5111222233334444"
}

### 3. Relatório Administrativo (O ataque N+1 / N*M no banco)
GET {{baseUrl}}/api/admin/financial-report

### 4. Deletar Usuário (Gera inconsistência no banco)
DELETE {{baseUrl}}/api/users/1